PSW/Controllers/AuthenticationController.cs
using PSW.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace PSW.Controllers
{
    public class AuthenticationController : Controller
    {
        PSWEntities context = new PSWEntities();
        // GET: Authentication
        public string GetIP()
        {
            string Str = "";
            Str = System.Net.Dns.GetHostName();
            IPHostEntry ipEntry = System.Net.Dns.GetHostEntry(Str);
            IPAddress[] addr = ipEntry.AddressList;
            return addr[addr.Length - 1].ToString();
        }
        public ActionResult Index()
        {
            Response.Cookies.Add(new HttpCookie("ASP.NET_SessionId", ""));
            return View();
        }
        [HttpPost]
        public ActionResult Index(CustomLogin db_table)
        {
            try
            {
                Session["IP"] = GetIP();
                PSW_LOGIN_MASTER login = context.PSW_LOGIN_MASTER.Where(m => m.LOG_USER_ID == db_table.LOG_USER_ID).FirstOrDefault();
                if (login != null)
                {
                    PSW_LOGIN loginview = context.PSW_LOGIN.Where(m => m.LOG_ID == login.LOG_ID).FirstOrDefault();

                    PSW_SYSTEM_SETUP SystemSetup = context.PSW_SYSTEM_SETUP.Where(m => m.SS_ID == 1).FirstOrDefault();
                    if (SystemSetup != null)
                    {
                        Session["IP"] = GetIP();
                        if (loginview != null && login.ASSIGNED_ROLES != null)
                        {
                            if (loginview.LOG_USER_STATUS == "Active")
                            {
                                if (!loginview.LOG_USER_ID.ToLower().Contains("admin"))
                                {
                                    if (loginview.LOG_USER_ID == db_table.LOG_USER_ID && loginview.LOG_ISAUTH == true)
                                    {
                                        string adPath = "";
                                        string adurl = "";
                                        if (db_table.DOMAIN_NAME == "APAC")
                                        {
                                            adPath = "LDAP://apac.nsroot.net"; //Fully-qualified Domain Name
                                            adurl = "apac.nsroot.net";
                                        }
                                        else if (db_table.DOMAIN_NAME == "EUR")
                                        {
                                            adPath = "LDAP://eur.nsroot.net"; //Fully-qualified Domain Name
                                            adurl = "eur.nsroot.net";
                                        }
                                        else if (db_table.DOMAIN_NAME == "NAM")
                                        {
                                            adPath = "LDAP://nam.nsroot.net"; //Fully-qualified Domain Name
                                            adurl = "nam.nsroot.net";
                                        }
                                        else
                                        {
                                            ViewBag.message = "Select the domain to continue.";
                                            return View();
                                        }
                                        //string adPath = "LDAP://eur.nsroot.net"; //Fully-qualified Domain Name
                                        LdapAuthentication adAuth = new LdapAuthentication(adPath);
                                        bool CheckAuth = adAuth.IsAuthenticated(adurl, db_table.LOG_USER_ID, db_table.LOG_PASSWORD);
                                        if (CheckAuth == true)
                                        {
                                            bool isCookiePersistent = User.Identity.IsAuthenticated;
                                            FormsAuthenticationTicket authTicket = new FormsAuthenticationTicket
                                                (1, db_table.LOG_USER_ID, DateTime.Now, DateTime.Now.AddMinutes(60), isCookiePersistent, null);
                                            string encryptedTicket = FormsAuthentication.Encrypt(authTicket);
                                            HttpCookie authCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket);
                                            if (true == isCookiePersistent)
                                                authCookie.Expires = authTicket.Expiration;
                                            Response.Cookies.Add(authCookie);
                                            PSW_LOGIN_LOG Log = new PSW_LOGIN_LOG();
                                            Log.LL_ID = Convert.ToInt32(context.PSW_LOGIN_LOG.Max(m => (decimal?)m.LL_ID)) + 1;
                                            Log.LL_USER_ID = loginview.LOG_USER_ID;
                                            Log.LL_LAST_LOGIN = DateTime.Now;
                                            context.PSW_LOGIN_LOG.Add(Log);
                                            context.SaveChanges();
                                            Session["USER_ID"] = loginview.LOG_USER_ID;
                                            Session["USER_NAME"] = loginview.LOG_USER_NAME;
                                            //Session["USER_TYPE"] = loginview.R_NAME;
                                            return RedirectToAction("Index", "Home");

                                        }
                                        else
                                        {
                                            ViewBag.message = "Authentication Failed from the Domain.";
                                        }
                                    }
                                    else
                                    {
                                        if (loginview.LOG_ISAUTH != true)
                                            ViewBag.message = "Unauthorize User : " + db_table.LOG_USER_ID + " is unauthorize";
                                        else if (loginview.LOG_USER_ID != db_table.LOG_USER_ID)
                                            ViewBag.message = "Invalid UserId : " + db_table.LOG_USER_ID + " is case sensetive";
                                        return View(db_table);
                                    }
                                }
                                else
                                {
                                    if (loginview.LOG_USER_ID == db_table.LOG_USER_ID && SystemSetup.SS_HASH == DAL.Encrypt(db_table.LOG_PASSWORD) && loginview.LOG_ISAUTH == true)
                                    {
                                        bool isCookiePersistent = User.Identity.IsAuthenticated;
                                        FormsAuthenticationTicket authTicket = new FormsAuthenticationTicket
                                               (1, db_table.LOG_USER_ID, DateTime.Now, DateTime.Now.AddMinutes(60), isCookiePersistent, null);
                                        string encryptedTicket = FormsAuthentication.Encrypt(authTicket);
                                        HttpCookie authCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket);
                                        if (true == isCookiePersistent)
                                            authCookie.Expires = authTicket.Expiration;
                                        Response.Cookies.Add(authCookie);
                                        PSW_LOGIN_LOG Log = new PSW_LOGIN_LOG();
                                        Log.LL_ID = Convert.ToInt32(context.PSW_LOGIN_LOG.Max(m => (decimal?)m.LL_ID)) + 1;
                                        Log.LL_USER_ID = loginview.LOG_USER_ID;
                                        Log.LL_LAST_LOGIN = DateTime.Now;
                                        context.PSW_LOGIN_LOG.Add(Log);
                                        context.SaveChanges();
                                        Session["USER_ID"] = loginview.LOG_USER_ID;
                                        Session["USER_NAME"] = loginview.LOG_USER_NAME;
                                        //Session["USER_TYPE"] = loginview.R_NAME;
                                        return RedirectToAction("Index", "Home");
                                    }
                                    else
                                    {
                                        if (SystemSetup.SS_HASH != DAL.Encrypt(db_table.LOG_PASSWORD))
                                            ViewBag.message = "Invalid Password : Invalid Password Provided for the User " + db_table.LOG_USER_ID;
                                        else if (loginview.LOG_ISAUTH != true)
                                            ViewBag.message = "Unauthorize User : " + db_table.LOG_USER_ID + " is unauthorize";
                                        else if (loginview.LOG_USER_ID != db_table.LOG_USER_ID)
                                            ViewBag.message = "Invalid UserId : " + db_table.LOG_USER_ID + " is case sensetive";
                                        return View(db_table);
                                    }
                                }
                            }
                            else
                            {
                                ViewBag.message = "User Id " + loginview.LOG_USER_ID + " is in de-active status.";
                                return View(db_table);
                            }
                        }
                        else
                        {
                            ViewBag.message = "Login Was Successfull but No Rights Assign to the User";
                            return View(db_table);
                        }
                    }

PSW/Views/Authentication/Index.cshtml
@model PSW.Models.CustomLogin

@{
    Layout = null;
    ViewBag.Title = "Login";

    if (ViewBag.message == "Logged In Successfully !" && ViewBag.message != null)
    {
        <div class="alert alert-success text-center" role="alert" id="messagebox">
            @ViewBag.message
            <button type="button" id="Btnclose" class="close" data-dismiss="alert"><span class="fa fa-times"></span></button>
        </div>
    }
    else if (ViewBag.message != "Logged In Successfully !" && ViewBag.message != null)
    {
        <div class="alert alert-warning text-center" id="messagebox" role="alert">
            @ViewBag.message
            <button type="button" id="Btnclose" class="close" data-dismiss="alert"><span class="fa fa-times"></span></button>
        </div>
    }
}
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <!-- External CSS libraries -->
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Content/Assets/Dashboard/plugins/fontawesome-free/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="~/Content/Assets/Dashboard/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Content/Assets/Dashboard/dist/css/adminlte.min.css">
    <link href="~/Content/Assets/Dashboard/dist/css/customstyle.css" rel="stylesheet" />
    <!-- SweetAlert2 -->
    <link rel="stylesheet" href="~/Content/Assets/Dashboard/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css">
</head>
<body class="hold-transition login-page">
    <div class="page_loader"></div>

    <div class="login-box">
        <!-- /.login-logo -->
        <div class="card card-outline card-primary">
            <div class="card-header text-center">
                <a href="@Url.Action("Index","Login")" class="h1"><img src="~/Content/Assets/Dashboard/dist/img/logo.jpg" height="70" width="100" alt="Citi Logo" /></a>
            </div>
            <div class="card-header text-center">
                <p class="heading-FX">PSW</p>
                <p class="Version-Text">Version 2.4.7</p>
            </div>
            <div class="card-body">
                <p class="Custom-Login-Font text-center">Sign in to your account</p>
                @using (Html.BeginForm("Index", "Authentication", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(m => m.LOG_ID)

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="input-group mb-3">
                        @Html.DropDownListFor(model => model.DOMAIN_NAME, new List<SelectListItem>
                                  { new SelectListItem{Text="EUR", Value="EUR"},
                                   new SelectListItem{Text="APAC", Value="APAC"},
                                   new SelectListItem{Text="NAM", Value="NAM"}}, "--Select Domain--", new { @class = "form-control select2 select2-primary" })
                    </div>
                    <div class="input-group mb-3">
                        @Html.EditorFor(model => model.LOG_USER_ID, new { htmlAttributes = new { @class = "form-control", @type = "text", @placeholder = "Enter User Name", @autocomplete = "off" } })
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        @Html.EditorFor(model => model.LOG_PASSWORD, new { htmlAttributes = new { @class = "form-control", @type = "password", @placeholder = "Enter Password", @autocomplete = "off" } })
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <!-- /.col -->
                        <div class="col-12">
                            <button type="submit" id="Login-Button" class="btn btn-primary btn-block">Sign In</button>
                        </div>
                        <!-- /.col -->
                    </div>
                }
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
    <!-- External JS libraries -->
    @*<script src="~/Content/Assets/Login/js/Custom.js"></script>*@
    <!-- jQuery -->
    <script src="~/Content/Assets/Dashboard/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/Content/Assets/Dashboard/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <!-- SweetAlert2 -->
    <script src="~/Content/Assets/Dashboard/plugins/sweetalert2/sweetalert2.min.js"></script>
    <script src="~/Content/Assets/Dashboard/dist/js/adminlte.min.js"></script>
    <!-- Custom JS Script -->
</body>
</html>